---
title: "Fairness Analysis Figures and Tables"
author: "Ariane Stark and Dasuni Jayawardena"
output:
  pdf_document: default
  html_document: default
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_format = "all") })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
library(tidyverse)
library(readr)
library(kableExtra)
library(cowplot)
library(png)
library(covidHubUtils)
library(zoltr)
#library(covidcast)
library("scales")

last_day_of_week_end_date <- "2021-03-06"

all_the_data_by_week_pull_cutoff <- 
  read_csv("data-output/all_the_data_by_week.csv")%>% 
  subset(select = -c(1)) %>% 
  filter(`last date of week` <= last_day_of_week_end_date)

all_the_data_by_week_relative_pull_cutoff <- 
  read_csv("data-output/all_the_data_by_week_relative.csv") %>% 
  subset(select = -c(1)) %>% 
  filter(`last date of week` <= last_day_of_week_end_date)

case_truth_and_predictions_pull_cutoff <-
  read_csv("data-output/case_truth_and_predictions.csv") %>% 
  subset(select = -c(1)) %>% 
  filter(source_date <= last_day_of_week_end_date)

national_case_truth_and_predictions_pull_cutoff <-
  read_csv("data-output/national_case_truth_and_predictions.csv") %>% 
  subset(select = -c(1))  %>% 
  filter(source_date <= last_day_of_week_end_date)


case_labeller <- function(variable,value) {
  return (paste0(as.character(value), " cases"))
}

```

```{r echo=FALSE}

all_the_data_pull_cutoff <- all_the_data_by_week_pull_cutoff %>% 
  group_by(FIPS_CODE) %>% 
  summarise_at(vars("4 week ahead absolute error","3 week ahead absolute error",
                    "2 week ahead absolute error","1 week ahead absolute error"),
               list("mean" = mean),
               na.rm = TRUE) %>% 
  rename("1 week ahead MAE" = 5) %>% 
  rename("2 week ahead MAE" = 4) %>% 
  rename("3 week ahead MAE" = 3) %>% 
  rename("4 week ahead MAE" = 2)

all_the_data_pull_cutoff <- left_join(all_the_data_pull_cutoff, 
             unique(all_the_data_by_week_pull_cutoff[c(1,26:34)]), by = "FIPS_CODE")


```

```{r echo=FALSE}

all_the_data_relative_pull_cutoff <- all_the_data_by_week_relative_pull_cutoff %>% 
  group_by(FIPS_CODE) %>% 
  summarise_at(vars("4 week ahead absolute error","3 week ahead absolute error",
                    "2 week ahead absolute error","1 week ahead absolute error",
                    "4 week ahead absolute error base",
                    "3 week ahead absolute error base",
                    "2 week ahead absolute error base",
                    "1 week ahead absolute error base"),
               list("mean" = mean),
               na.rm = TRUE) %>% 
  rename("1 week ahead MAE" = 5) %>% 
  rename("2 week ahead MAE" = 4) %>% 
  rename("3 week ahead MAE" = 3) %>% 
  rename("4 week ahead MAE" = 2) %>% 
  rename("1 week ahead MAE base" = 9) %>% 
  rename("2 week ahead MAE base" = 8) %>% 
  rename("3 week ahead MAE base" = 7) %>% 
  rename("4 week ahead MAE base" = 6)

all_the_data_relative_pull_cutoff <- left_join(all_the_data_relative_pull_cutoff, 
             unique(all_the_data_by_week_relative_pull_cutoff[c(1,18:26)]), 
             by = "FIPS_CODE") %>% 
  mutate("1 week RMAE" = `1 week ahead MAE`/
           `1 week ahead MAE base`) %>% 
  mutate("2 week RMAE" = `2 week ahead MAE`/
           `2 week ahead MAE base`) %>% 
  mutate("3 week RMAE" = `3 week ahead MAE`/
           `3 week ahead MAE base`) %>% 
  mutate("4 week RMAE" = `4 week ahead MAE`/
           `4 week ahead MAE base`) %>% 
  filter(!is.na(Total_Pop))


```

## Data Editing 
```{r}
## number of counties with 0 reported cummulative cases
## 22 Utah 2 Alaska 1 Hawaii
nrow(all_the_data_pull_cutoff %>% filter(`total cases`==0))

## remove these counties so RMAE avoids a divide by zero
all_the_data_pull_cutoff <- all_the_data_pull_cutoff %>% 
  filter(`total cases`!=0)
all_the_data_relative_pull_cutoff <- all_the_data_relative_pull_cutoff %>%
  filter(`total cases`!=0)
```
## Important Values
```{r}
all_the_data_pull_cutoff <- all_the_data_pull_cutoff %>% 
  mutate("Case Quartile" = cut_number(`total cases`,n=4,labels=FALSE) )

## 1 Week MAE Lowest 25%
dat <- all_the_data_pull_cutoff %>% 
  filter(`Case Quartile`==1)
round(mean(dat$`1 week ahead MAE`),2)

## 1 Week MAE Highest 25%
dat <- all_the_data_pull_cutoff %>% 
  filter(`Case Quartile`==4)
round(mean(dat$`1 week ahead MAE`),2)

remove(dat)
```

```{r}
table_dat <- all_the_data_pull_cutoff %>% 
  mutate("Black Prop. Quartile" = cut_number(Total_Black/Total_Pop,n=4,labels=FALSE) ) %>% 
  select(c(`1 week ahead MAE`,`Case Quartile`,`Black Prop. Quartile`))

table_by_2_dif_quart <- matrix(nrow = 4, ncol = 4)
dimnames(table_by_2_dif_quart ) <-
  list("Case Quartile" = c("lowest 25%", "Q2","Q3","highest 25%"),
                    "Prop. Black Quartile" = c("lowest 25%", "Q2","Q3","highest 25%"))
for (i in 1:4) {
  for (j in 1:4) {
    vals <- table_dat %>% 
      filter(`Black Prop. Quartile`==j) %>% 
      filter(`Case Quartile`==i)
    table_by_2_dif_quart [i,j] <- round(median(vals$`1 week ahead MAE`),3)
  }
}
table_by_2_dif_quart
```

```{r}
table_dat_rmae <- all_the_data_relative_pull_cutoff %>% 
  mutate("Black Prop. Quartile" = cut_number(Total_Black/Total_Pop,n=4,labels=FALSE) ) %>% 
mutate("Case Quartile" = cut_number(`total cases`,n=4,labels=FALSE)) %>% 
  select(c(`1 week RMAE`,`Case Quartile`,`Black Prop. Quartile`)) 

table_by_2_dif_quart_rmae <- matrix(nrow = 4, ncol = 4)
dimnames(table_by_2_dif_quart_rmae ) <-
  list("Case Quartile" = c("lowest 25%", "Q2","Q3","highest 25%"),
                    "Prop. Black Quartile" = c("lowest 25%", "Q2","Q3","highest 25%"))
for (i in 1:4) {
  for (j in 1:4) {
    vals <- table_dat_rmae %>% 
      filter(`Black Prop. Quartile`==j) %>% 
      filter(`Case Quartile`==i)
    table_by_2_dif_quart_rmae [i,j] <- round(median(vals$`1 week RMAE`),3)
  }
}
table_by_2_dif_quart_rmae
```


# Figures


### Figure 1

```{r include=FALSE}
fips1 = "13121"
fips2 = "25015"
county_1 <- "Fulton County, \n Georgia"
county_2 <- "Hampshire County,  \n Massachusetts"
dates_to_use <- c("2020-08-03","2020-10-05","2020-12-07","2021-02-01")

plot_data_forecasts <- read_csv("data-output/plot_data_forecasts.csv") %>% 
  subset(select = -c(1)) %>% 
  transform("location"=as.character(location))

plot_data_forecasts <- plot_data_forecasts%>% 
  rename("FIPS_CODE"="location") %>% 
  filter(FIPS_CODE %in% c(fips1,fips2)) %>% 
  mutate("last date of week forecast made" = 
           target_end_date-7*as.numeric(horizon)) %>% 
  select(FIPS_CODE,1:7,`last date of week forecast made`,10)

plot_data_truth <- all_the_data_by_week_pull_cutoff %>% 
  filter(FIPS_CODE %in% c(fips1,fips2)) %>% 
  rename("target_end_date" = 3) %>% 
  select(c(1:5))

plot_data <- right_join(plot_data_truth,plot_data_forecasts) %>% 
  mutate("AE" = abs(value - `true num incidence cases`) )
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
im1_fips1 <- plot_data_truth %>% 
  filter(FIPS_CODE == fips1)%>% 
  ggplot(mapping = aes(x=target_end_date, 
                           y=`true num incidence cases`)) +
  geom_point() +
  geom_line() +
  geom_point(mapping = aes(x=target_end_date, 
                           y=value,
                           color=model),
             data=plot_data_forecasts %>% filter(FIPS_CODE==fips1))+
  geom_line(mapping = aes(x=target_end_date, 
                           y=value,
                           color=model,
                           group= model,
                          group = `last date of week forecast made`),
             data=plot_data_forecasts %>% filter(FIPS_CODE==fips1) %>% 
              filter(forecast_date == dates_to_use[1]))+
  geom_line(mapping = aes(x=target_end_date, 
                           y=value,
                           color=model,
                           group= model,
                          group = `last date of week forecast made`),
             data=plot_data_forecasts %>% filter(FIPS_CODE==fips1) %>% 
              filter(forecast_date == dates_to_use[2]))+
  geom_line(mapping = aes(x=target_end_date, 
                           y=value,
                           color=model,
                           group= model,
                          group = `last date of week forecast made`),
             data=plot_data_forecasts %>% filter(FIPS_CODE==fips1) %>% 
              filter(forecast_date == dates_to_use[3]))+
  geom_line(mapping = aes(x=target_end_date, 
                           y=value,
                           color=model,
                           group= model,
                          group = `last date of week forecast made`),
             data=plot_data_forecasts %>% filter(FIPS_CODE==fips1) %>% 
              filter(forecast_date == dates_to_use[4]))+
  xlab("") + 
  ylab("Cases") +
  ylim(0,6000) +
  theme(legend.position = "none") + 
  labs(title = county_1) 



im2_fips1 <- plot_data %>% 
  filter(horizon == 1) %>% 
  filter(FIPS_CODE == fips1) %>% 
  ggplot() +
    geom_point(mapping = aes(x=target_end_date, y= AE,color=model))+
  xlab("Date") + 
  ylab("1 Week Ahead Abs. Error") +
  ylim(0,1300) +
  theme(legend.position = "none") 


im1_fips2 <- plot_data_truth %>% 
  filter(FIPS_CODE == fips2)%>% 
  ggplot(mapping = aes(x=target_end_date, 
                           y=`true num incidence cases`)) +
  geom_point() +
  geom_line() +
  geom_point(mapping = aes(x=target_end_date, 
                           y=value,
                           color=model),
             data=plot_data_forecasts %>% filter(FIPS_CODE==fips2))+
  geom_line(mapping = aes(x=target_end_date, 
                           y=value,
                           color=model,
                           group= model,
                          group = `last date of week forecast made`),
             data=plot_data_forecasts %>% filter(FIPS_CODE==fips2) %>% 
              filter(forecast_date == dates_to_use[1]))+
  geom_line(mapping = aes(x=target_end_date, 
                           y=value,
                           color=model,
                           group= model,
                          group = `last date of week forecast made`),
             data=plot_data_forecasts %>% filter(FIPS_CODE==fips2) %>% 
              filter(forecast_date == dates_to_use[2]))+
  geom_line(mapping = aes(x=target_end_date, 
                           y=value,
                           color=model,
                           group= model,
                          group = `last date of week forecast made`),
             data=plot_data_forecasts %>% filter(FIPS_CODE==fips2) %>% 
              filter(forecast_date == dates_to_use[3]))+
  geom_line(mapping = aes(x=target_end_date, 
                           y=value,
                           color=model,
                           group= model,
                          group = `last date of week forecast made`),
             data=plot_data_forecasts %>% filter(FIPS_CODE==fips2) %>% 
              filter(forecast_date == dates_to_use[4]))+
  xlab("") + 
  ylab("") +
  ylim(0,6000) +
  theme(legend.position = "none")+ 
  labs(title = county_2) 




im2_fips2 <- plot_data %>% 
  filter(horizon == 1) %>% 
  filter(FIPS_CODE == fips2) %>% 
  ggplot() +
    geom_point(mapping = aes(x=target_end_date, y= AE,color=model))+
  xlab("Date") + 
  ylab("") +
  ylim(0,1300) + 
  theme(legend.position = "none") 

plots <- plot_grid(im1_fips1,  im1_fips2, im2_fips1,im2_fips2, 
          labels = "auto" ,label_size = 10 ,label_x = 0.06,label_y = 1)
legend <- get_legend(im1_fips1 + 
                       guides(color = guide_legend(nrow = 1)) +
                       theme(legend.position = "bottom"))
plot_grid(plots, legend, ncol = 1, rel_heights = c(1, .1))
```


### Figure 2

```{r echo=FALSE}
im1 <- all_the_data_pull_cutoff %>% 
  ggplot()+
  geom_boxplot(aes(x=cut_number(Total_Black/Total_Pop,4), 
      y=`1 week ahead MAE`)) +
  xlab("") + 
  ylab("Log Scale 1 \n Week Ahead MAE") +
  scale_y_log10()

im2 <- all_the_data_pull_cutoff %>% 
  ggplot()+
  geom_boxplot(aes(x=cut_number(Total_Black/Total_Pop,4), 
      y=`1 week ahead MAE`, fill=as.factor(cut_number(`total cases`,n=4)))) +
  xlab("Proportion of Black Constituents") +
  ylab("Log Scale 1  \n Week Ahead MAE")+
  labs(fill="Case Quartile")+
  scale_y_log10() +
  theme(legend.position = "none")

plots <- plot_grid(im1,im2, labels = "auto" ,ncol=1, 
                   label_size = 10 ,label_x = 0.09,label_y = 1)
legend <- get_legend(im2 + 
                       guides(color = guide_legend(nrow = 1)) +
                       theme(legend.position = "bottom"))
plot_grid(plots, legend, ncol = 1, rel_heights = c(1, .1))
```



### Figure 3: 1 and 4 week MAE and RMAE for Racial Demographics
```{r echo=FALSE, message=FALSE, warning=FALSE}

#mae

im1 <- all_the_data_pull_cutoff %>% 
  ggplot() + 
  aes(x=Total_Black/Total_Pop, y=`1 week ahead MAE`) +
  geom_point(aes(color=cut_number(`total cases`,n=4)),
               alpha=0.25)+
  geom_smooth(aes(color=cut_number(`total cases`,n=4)),
                se=FALSE) +
  geom_smooth(se=FALSE, color="black") + 
  xlab("") + 
  ylab("1 Wk. Ahead MAE") +
  guides(color=guide_legend(title="Case Quartiles")) +
  #ylim(0,12000) +
  scale_y_log10(limits = c(NA,1200))+
  theme(legend.position = "none")

im2 <- all_the_data_pull_cutoff %>% 
  ggplot() + 
  aes(x=Total_Black/Total_Pop, y=`4 week ahead MAE`) +
  geom_point(aes(color=cut_number(`total cases`,n=4)),
               alpha=0.25)+
  geom_smooth(aes(color=cut_number(`total cases`,n=4)),
                se=FALSE) +
  geom_smooth(se=FALSE, color="black") + 
  xlab("Prop Black Constituents") + 
  ylab("4 Wk. Ahead MAE") +
  guides(color=guide_legend(title="Case Quartiles")) +
  #ylim(0,12000) +
  scale_y_log10(limits = c(NA,1200))+
  theme(legend.position = "none")



# rmae
im3 <- all_the_data_relative_pull_cutoff %>% 
  ggplot() + 
  aes(x=Total_Black/Total_Pop, y=`1 week RMAE`) +
  geom_point(aes(color=cut_number(`total cases`,n=4)),
               alpha=0.25)+
  geom_smooth(aes(color=cut_number(`total cases`,n=4)),
                se=FALSE) +
  geom_smooth(se=FALSE, color="black") + 
  xlab("") + 
  ylab("1 Wk. RMAE") +
  guides(color=guide_legend(title="Case Quartiles")) +
  scale_y_log10(limits = c(0.1,3.5)) +
  theme(legend.position = "none")

im4 <- all_the_data_relative_pull_cutoff %>% 
  ggplot() + 
  aes(x=Total_Black/Total_Pop, y=`4 week RMAE`) +
  geom_point(aes(color=cut_number(`total cases`,n=4)),
               alpha=0.25)+
  geom_smooth(aes(color=cut_number(`total cases`,n=4)),
                se=FALSE) +
  geom_smooth(se=FALSE, color="black") + 
  xlab("Prop Black Constituents") + 
  ylab("4 Wk. RMAE") +
  labs(color="Case Quartile")+
  scale_y_log10(limits = c(0.1,3.5)) +
  theme(legend.position = "none")


plots <- plot_grid(im1,im3,im2,im4, labels = "auto" ,
                   label_size = 10 ,label_x = 0.03,label_y = 1)
legend <- get_legend(im4 + 
                       guides(color = guide_legend(nrow = 1)) +
                       theme(legend.position = "bottom"))
plot_grid(plots, legend, ncol = 1, rel_heights = c(1, .1))
```




### Figure 3 option 2: 1 and 4 week MAE and RMAE for Racial Demographics
```{r echo=FALSE, message=FALSE, warning=FALSE}

#mae

mae_1wk_comb <- all_the_data_pull_cutoff %>% 
  ggplot() + 
  aes(x=Total_Black/Total_Pop, y=`1 week ahead MAE`) +
  geom_point(aes(color=cut_number(`total cases`,n=4)),
               alpha=0.25)+
  geom_smooth(aes(color=cut_number(`total cases`,n=4)),
                se=FALSE) +
  geom_smooth(se=FALSE, color="black") + 
  xlab("") + 
  ylab("1 Wk. Ahead MAE") +
  guides(color=guide_legend(title="Case Quartiles")) +
  #ylim(0,12000) +
  scale_y_log10(limits = c(.01,1200))+
  theme(legend.position = "none")

mae_1wk_q1 <- all_the_data_pull_cutoff %>% 
  mutate(Case_Quart = cut_number(`total cases`,n=4, labels=FALSE)) %>% 
  filter(Case_Quart == 1) %>% 
  ggplot() + 
  aes(x=Total_Black/Total_Pop, y=`1 week ahead MAE`) +
  geom_point(color=hue_pal()(4)[1],
               alpha=0.25) +
  geom_smooth(color=hue_pal()(4)[1],
                se=FALSE) +
  #geom_smooth(se=FALSE, color="black") + 
  xlab("") + 
  #ylab("1 Wk. Ahead MAE") +
  guides(color=guide_legend(title="Case Quartiles")) +
  scale_y_log10(limits = c(.01,1200))+
  theme(legend.position = "none")

mae_1wk_q2 <- all_the_data_pull_cutoff %>% 
  mutate(Case_Quart = cut_number(`total cases`,n=4, labels=FALSE)) %>% 
  filter(Case_Quart == 2) %>% 
  ggplot() + 
  aes(x=Total_Black/Total_Pop, y=`1 week ahead MAE`) +
  geom_point(color=hue_pal()(4)[2],
               alpha=0.25) +
  geom_smooth(color=hue_pal()(4)[2],
                se=FALSE) +
  #geom_smooth(se=FALSE, color="black") + 
  xlab("") + 
  #ylab("1 Wk. Ahead MAE") +
  guides(color=guide_legend(title="Case Quartiles")) +
  scale_y_log10(limits = c(.01,1200))+
  theme(legend.position = "none")

mae_1wk_q3 <- all_the_data_pull_cutoff %>% 
  mutate(Case_Quart = cut_number(`total cases`,n=4, labels=FALSE)) %>% 
  filter(Case_Quart == 3) %>% 
  ggplot() + 
  aes(x=Total_Black/Total_Pop, y=`1 week ahead MAE`) +
  geom_point(color=hue_pal()(4)[3],
               alpha=0.25) +
  geom_smooth(color=hue_pal()(4)[3],
                se=FALSE) +
  #geom_smooth(se=FALSE, color="black") + 
  xlab("") + 
  #ylab("1 Wk. Ahead MAE") +
  guides(color=guide_legend(title="Case Quartiles")) +
  scale_y_log10(limits = c(.01,1200))+
  theme(legend.position = "none")

mae_1wk_q4 <- all_the_data_pull_cutoff %>% 
  mutate(Case_Quart = cut_number(`total cases`,n=4, labels=FALSE)) %>% 
  filter(Case_Quart == 4) %>% 
  ggplot() + 
  aes(x=Total_Black/Total_Pop, y=`1 week ahead MAE`) +
  geom_point(color=hue_pal()(4)[4],
               alpha=0.25) +
  geom_smooth(color=hue_pal()(4)[4],
                se=FALSE) +
  #geom_smooth(se=FALSE, color="black") + 
  xlab("") + 
  #ylab("1 Wk. Ahead MAE") +
  guides(color=guide_legend(title="Case Quartiles")) +
  scale_y_log10(limits = c(.01,1200))+
  theme(legend.position = "none")


mae_4wk_comb <- all_the_data_pull_cutoff %>% 
  ggplot() + 
  aes(x=Total_Black/Total_Pop, y=`4 week ahead MAE`) +
  geom_point(aes(color=cut_number(`total cases`,n=4)),
               alpha=0.25)+
  geom_smooth(aes(color=cut_number(`total cases`,n=4)),
                se=FALSE) +
  geom_smooth(se=FALSE, color="black") + 
  xlab("Prop Black Constituents") + 
  ylab("4 Wk. Ahead MAE") +
  guides(color=guide_legend(title="Case Quartiles")) +
  #ylim(0,12000) +
  scale_y_log10(limits = c(.01,1200))+
  theme(legend.position = "none")

mae_4wk_q1 <- all_the_data_pull_cutoff %>% 
  mutate(Case_Quart = cut_number(`total cases`,n=4, labels=FALSE)) %>% 
  filter(Case_Quart == 1) %>% 
  ggplot() + 
  aes(x=Total_Black/Total_Pop, y=`4 week ahead MAE`) +
  geom_point(color=hue_pal()(4)[1],
               alpha=0.25) +
  geom_smooth(color=hue_pal()(4)[1],
                se=FALSE) + 
  #geom_smooth(se=FALSE, color="black") + 
  xlab("") + 
  #ylab("4 Wk. Ahead MAE") +
  guides(color=guide_legend(title="Case Quartiles")) +
  scale_y_log10(limits = c(.01,1200))+
  theme(legend.position = "none")

mae_4wk_q2 <- all_the_data_pull_cutoff %>% 
  mutate(Case_Quart = cut_number(`total cases`,n=4, labels=FALSE)) %>% 
  filter(Case_Quart == 2) %>% 
  ggplot() + 
  aes(x=Total_Black/Total_Pop, y=`4 week ahead MAE`) +
  geom_point(color=hue_pal()(4)[2],
               alpha=0.25) +
  geom_smooth(color=hue_pal()(4)[2],
                se=FALSE) +
  #geom_smooth(se=FALSE, color="black") + 
  xlab("") + 
  #ylab("4 Wk. Ahead MAE") +
  guides(color=guide_legend(title="Case Quartiles")) +
  scale_y_log10(limits = c(.01,1200))+
  theme(legend.position = "none")

mae_4wk_q3 <- all_the_data_pull_cutoff %>% 
  mutate(Case_Quart = cut_number(`total cases`,n=4, labels=FALSE)) %>% 
  filter(Case_Quart == 3) %>% 
  ggplot() + 
  aes(x=Total_Black/Total_Pop, y=`4 week ahead MAE`) +
  geom_point(color=hue_pal()(4)[3],
               alpha=0.25) +
  geom_smooth(color=hue_pal()(4)[3],
                se=FALSE) +
  #geom_smooth(se=FALSE, color="black") + 
  xlab("") + 
  #ylab("4 Wk. Ahead MAE") +
  guides(color=guide_legend(title="Case Quartiles")) +
  scale_y_log10(limits = c(.01,1200))+
  theme(legend.position = "none")

mae_4wk_q4 <- all_the_data_pull_cutoff %>% 
  mutate(Case_Quart = cut_number(`total cases`,n=4, labels=FALSE)) %>% 
  filter(Case_Quart == 4) %>% 
  ggplot() + 
  aes(x=Total_Black/Total_Pop, y=`4 week ahead MAE`) +
  geom_point(color=hue_pal()(4)[4],
               alpha=0.25) +
  geom_smooth(color=hue_pal()(4)[4],
                se=FALSE) +
  #geom_smooth(se=FALSE, color="black") + 
  xlab("") + 
  #ylab("4 Wk. Ahead MAE") +
  guides(color=guide_legend(title="Case Quartiles")) +
  scale_y_log10(limits = c(.01,1200))+
  theme(legend.position = "none")

# rmae
rmae_1wk_comb <- all_the_data_relative_pull_cutoff %>% 
  ggplot() + 
  aes(x=Total_Black/Total_Pop, y=`1 week RMAE`) +
  geom_point(aes(color=cut_number(`total cases`,n=4)),
               alpha=0.25)+
  geom_smooth(aes(color=cut_number(`total cases`,n=4)),
                se=FALSE) +
  geom_smooth(se=FALSE, color="black") + 
  xlab("") + 
  ylab("1 Wk. RMAE") +
  guides(color=guide_legend(title="Case Quartiles")) +
  scale_y_log10(limits = c(0.1,3.5)) +
  theme(legend.position = "none")

rmae_1wk_q1 <- all_the_data_relative_pull_cutoff %>% 
  mutate(Case_Quart = cut_number(`total cases`,n=4, labels=FALSE)) %>% 
  filter(Case_Quart == 1) %>% 
  ggplot() + 
  aes(x=Total_Black/Total_Pop, y=`1 week RMAE`) +
  geom_point(color=hue_pal()(4)[1],
               alpha=0.25) +
  geom_smooth(color=hue_pal()(4)[1],
                se=FALSE) +
  #geom_smooth(se=FALSE, color="black") + 
  xlab("") + 
  #ylab("1 Wk. RMAE") +
  guides(color=guide_legend(title="Case Quartiles")) +
  scale_y_log10(limits = c(0.1,3.5)) +
  theme(legend.position = "none")

rmae_1wk_q2 <- all_the_data_relative_pull_cutoff %>% 
  mutate(Case_Quart = cut_number(`total cases`,n=4, labels=FALSE)) %>% 
  filter(Case_Quart == 2) %>% 
  ggplot() + 
  aes(x=Total_Black/Total_Pop, y=`1 week RMAE`) +
  geom_point(color=hue_pal()(4)[2],
               alpha=0.25) +
  geom_smooth(color=hue_pal()(4)[2],
                se=FALSE) +
  #geom_smooth(se=FALSE, color="black") + 
  xlab("") + 
  #ylab("1 Wk. RMAE") +
  guides(color=guide_legend(title="Case Quartiles")) +
  scale_y_log10(limits = c(0.1,3.5)) +
  theme(legend.position = "none")

rmae_1wk_q3 <- all_the_data_relative_pull_cutoff %>% 
  mutate(Case_Quart = cut_number(`total cases`,n=4, labels=FALSE)) %>% 
  filter(Case_Quart == 3) %>% 
  ggplot() + 
  aes(x=Total_Black/Total_Pop, y=`1 week RMAE`) +
  geom_point(color=hue_pal()(4)[3],
               alpha=0.25) +
  geom_smooth(color=hue_pal()(4)[3],
                se=FALSE) +
  #geom_smooth(se=FALSE, color="black") + 
  xlab("") + 
  #ylab("1 Wk. RMAE") +
  guides(color=guide_legend(title="Case Quartiles")) +
  scale_y_log10(limits = c(0.1,3.5)) +
  theme(legend.position = "none")

rmae_1wk_q4 <- all_the_data_relative_pull_cutoff %>% 
  mutate(Case_Quart = cut_number(`total cases`,n=4, labels=FALSE)) %>% 
  filter(Case_Quart == 4) %>% 
  ggplot() + 
  aes(x=Total_Black/Total_Pop, y=`1 week RMAE`) +
  geom_point(color=hue_pal()(4)[4],
               alpha=0.25) +
  geom_smooth(color=hue_pal()(4)[4],
                se=FALSE) +
  #geom_smooth(se=FALSE, color="black") + 
  xlab("") + 
  #ylab("1 Wk. RMAE") +
  guides(color=guide_legend(title="Case Quartiles")) +
  scale_y_log10(limits = c(0.1,3.5)) +
  theme(legend.position = "none")

rmae_4wk_comb <- all_the_data_relative_pull_cutoff %>% 
  ggplot() + 
  aes(x=Total_Black/Total_Pop, y=`4 week RMAE`) +
  geom_point(aes(color=cut_number(`total cases`,n=4)),
               alpha=0.25)+
  geom_smooth(aes(color=cut_number(`total cases`,n=4)),
                se=FALSE) +
  geom_smooth(se=FALSE, color="black") + 
  xlab("Prop Black Constituents") + 
  ylab("4 Wk. RMAE") +
  labs(color="Case Quartile")+
  scale_y_log10(limits = c(0.1,3.5)) +
  theme(legend.position = "none")

rmae_4wk_q1 <- all_the_data_relative_pull_cutoff %>% 
  mutate(Case_Quart = cut_number(`total cases`,n=4, labels=FALSE)) %>% 
  filter(Case_Quart == 1) %>% 
  ggplot() + 
  aes(x=Total_Black/Total_Pop, y=`4 week RMAE`) +
  geom_point(color=hue_pal()(4)[1],
               alpha=0.25) +
  geom_smooth(color=hue_pal()(4)[1],
                se=FALSE) +
  #geom_smooth(se=FALSE, color="black") + 
  xlab("") + 
  #ylab("4 Wk. RMAE") +
  guides(color=guide_legend(title="Case Quartiles")) +
  scale_y_log10(limits = c(0.1,3.5)) +
  theme(legend.position = "none")

rmae_4wk_q2 <- all_the_data_relative_pull_cutoff %>% 
  mutate(Case_Quart = cut_number(`total cases`,n=4, labels=FALSE)) %>% 
  filter(Case_Quart == 2) %>% 
  ggplot() + 
  aes(x=Total_Black/Total_Pop, y=`4 week RMAE`) +
  geom_point(color=hue_pal()(4)[2],
               alpha=0.25) +
  geom_smooth(color=hue_pal()(4)[2],
                se=FALSE) +
  #geom_smooth(se=FALSE, color="black") + 
  xlab("") + 
  #ylab("4 Wk. RMAE") +
  guides(color=guide_legend(title="Case Quartiles")) +
  scale_y_log10(limits = c(0.1,3.5)) +
  theme(legend.position = "none")


rmae_4wk_q3 <- all_the_data_relative_pull_cutoff %>% 
  mutate(Case_Quart = cut_number(`total cases`,n=4, labels=FALSE)) %>% 
  filter(Case_Quart == 3) %>% 
  ggplot() + 
  aes(x=Total_Black/Total_Pop, y=`4 week RMAE`) +
  geom_point(color=hue_pal()(4)[3],
               alpha=0.25) +
  geom_smooth(color=hue_pal()(4)[3],
                se=FALSE) +
  #geom_smooth(se=FALSE, color="black") + 
  xlab("") + 
  #ylab("4 Wk. RMAE") +
  guides(color=guide_legend(title="Case Quartiles")) +
  scale_y_log10(limits = c(0.1,3.5)) +
  theme(legend.position = "none")

rmae_4wk_q4 <- all_the_data_relative_pull_cutoff %>% 
  mutate(Case_Quart = cut_number(`total cases`,n=4, labels=FALSE)) %>% 
  filter(Case_Quart == 4) %>% 
  ggplot() + 
  aes(x=Total_Black/Total_Pop, y=`4 week RMAE`) +
  geom_point(color=hue_pal()(4)[4],
               alpha=0.25) +
  geom_smooth(color=hue_pal()(4)[4],
                se=FALSE) +
  #geom_smooth(se=FALSE, color="black") + 
  xlab("") + 
  ylab("") +
  guides(color=guide_legend(title="Case Quartiles")) +
  scale_y_log10(limits = c(0.1,3.5)) +
  theme(legend.position = "none")


plots <- plot_grid(mae_1wk_comb, mae_1wk_q1, mae_1wk_q2,
                   mae_4wk_q3, mae_1wk_q4,
                   mae_4wk_comb, mae_4wk_q1, mae_4wk_q2,
                   mae_4wk_q3, mae_4wk_q4,
                   rmae_1wk_comb, rmae_1wk_q1, rmae_1wk_q2,
                   rmae_1wk_q3, rmae_1wk_q4,
                   rmae_4wk_comb, rmae_4wk_q1, rmae_4wk_q2,
                   rmae_4wk_q3, rmae_4wk_q4,
                   nrow = 4,
                   labels = "auto" ,
                   label_size = 10 ,label_x = 0.03,label_y = 1)
legend <- get_legend(mae_1wk_comb + 
                       guides(color = guide_legend(nrow = 1)) +
                       theme(legend.position = "bottom"))
plot_grid(plots, legend, ncol = 1, rel_heights = c(1, .1))
```

### Figure 4: 1 and 4 week MAE and RMAE for Poverty
```{r echo=FALSE}
im1 <- all_the_data_pull_cutoff %>% 
  ggplot() + 
  aes(x=Total_Households_Below_Poverty/(Total_Households_Below_Poverty+
                                          Total_Households_Above_Poverty), 
      y=`1 week ahead MAE`) +
  geom_point(aes(color=cut_number(`total cases`,n=4)),
               alpha=0.25)+
  geom_smooth(aes(color=cut_number(`total cases`,n=4)),
                se=FALSE) +
  geom_smooth(se=FALSE, color="black") + 
  xlab("") + 
  ylab("1 Wk. Ahead MAE") +
  guides(color=guide_legend(title="Case Quartiles")) +
  #ylim(0,12000) +
  scale_y_log10(limits = c(NA,1200))+
  theme(legend.position = "none")

im2 <- all_the_data_pull_cutoff %>% 
  ggplot() + 
  aes(x=Total_Households_Below_Poverty/(Total_Households_Below_Poverty+
                                          Total_Households_Above_Poverty), 
      y=`4 week ahead MAE`) +
  geom_point(aes(color=cut_number(`total cases`,n=4)),
               alpha=0.25)+
  geom_smooth(aes(color=cut_number(`total cases`,n=4)),
                se=FALSE) +
  geom_smooth(se=FALSE, color="black") + 
  xlab("Prop Households in Poverty") + 
  ylab("4 Wk. Ahead MAE") +
  guides(color=guide_legend(title="Case Quartiles")) +
  #ylim(0,12000) +
  scale_y_log10(limits = c(NA,1200))+
  theme(legend.position = "none")


# rmae
im3 <-all_the_data_relative_pull_cutoff %>% 
  ggplot() + 
  aes(x=Total_Households_Below_Poverty/(Total_Households_Below_Poverty+
                                          Total_Households_Above_Poverty), 
      y=`1 week RMAE`) +
  geom_point(aes(color=cut_number(`total cases`,n=4)),
               alpha=0.25)+
  geom_smooth(aes(color=cut_number(`total cases`,n=4)),
                se=FALSE) +
  geom_smooth(se=FALSE, color="black") + 
  xlab("") + 
  ylab("1 Wk. RMAE") +
  guides(color=guide_legend(title="Case Quartiles")) +
  scale_y_log10(limits = c(0.1,3.5)) +
  theme(legend.position = "none")

im4 <- all_the_data_relative_pull_cutoff %>% 
  ggplot() + 
  aes(x=Total_Households_Below_Poverty/(Total_Households_Below_Poverty+
                                          Total_Households_Above_Poverty), 
      y=`4 week RMAE`) +
  geom_point(aes(color=cut_number(`total cases`,n=4)),
               alpha=0.25)+
  geom_smooth(aes(color=cut_number(`total cases`,n=4)),
                se=FALSE) +
  geom_smooth(se=FALSE, color="black") + 
  xlab("Prop Households in Poverty") + 
  ylab("4 Wk. RMAE") +
  labs(color="Case Quartiles") +
  scale_y_log10(limits = c(0.1,3.5)) +
  theme(legend.position = "none")

plots <- plot_grid(im1,im3,im2,im4, labels = "auto",
                   label_size = 10 ,label_x = 0.03,label_y = 1)
legend <- get_legend(im4 + 
                       guides(color = guide_legend(nrow = 1)) +
                       theme(legend.position = "bottom"))
plot_grid(plots, legend, ncol = 1, rel_heights = c(1, .1))
```



# Tables

### Table 1
```{r echo=FALSE, message=FALSE, warning=FALSE}

regressionData<-data.frame(all_the_data_pull_cutoff$FIPS_CODE, 
                           all_the_data_pull_cutoff$Total_Pop,
                 all_the_data_pull_cutoff$Total_Black/all_the_data_pull_cutoff$Total_Pop,
                 all_the_data_pull_cutoff$`total cases`,
                 all_the_data_pull_cutoff$Total_Households_Below_Poverty/
                   (all_the_data_pull_cutoff$Total_Households_Below_Poverty+
                      all_the_data_pull_cutoff$Total_Households_Above_Poverty),
                    (all_the_data_pull_cutoff$`total cases`/
                       all_the_data_pull_cutoff$Total_Pop)*1,
                 all_the_data_pull_cutoff$`1 week ahead MAE`,
                 all_the_data_pull_cutoff$`4 week ahead MAE`
                 ) %>% 
  rename("Tot_Pop"=2) %>% 
  rename("Tot_Cases" = 4) %>% 
  rename("Prop_Black" = 3) %>% 
  rename("Prop_Pov" = 5) %>% 
  rename("Prop_Cases" = 6) %>% 
  rename("One_Week_MAE" = 7) %>% 
  rename("Four_Week_MAE" = 8)


dataMatrix <- matrix(c(round(summary(lm(One_Week_MAE~Prop_Black*Prop_Pov, 
                                  data = regressionData))$r.squared,4),
                       round(summary(lm(One_Week_MAE~Tot_Pop, 
                                  data = regressionData))$r.squared,4),
                       round(summary(lm(One_Week_MAE~Tot_Cases, 
                                  data = regressionData))$r.squared,4),
                       round(summary(lm(One_Week_MAE~Tot_Cases+
                                          Prop_Black*Prop_Pov, 
                                  data = regressionData))$r.squared,4),
                       round(summary(lm(Four_Week_MAE~Prop_Black*Prop_Pov, 
                                  data = regressionData))$r.squared,4),
                       round(summary(lm(Four_Week_MAE~Tot_Pop, 
                                  data = regressionData))$r.squared,4),
                       round(summary(lm(Four_Week_MAE~Tot_Cases, 
                                  data = regressionData))$r.squared,4),
                       round(summary(lm(Four_Week_MAE~Tot_Cases+
                                          Prop_Black*Prop_Pov, 
                                  data = regressionData))$r.squared,4)
                       ),ncol=1)
colnames(dataMatrix) <- c("R squared")
rownames(dataMatrix) <- c("1 wk Ahead MAE as a funct. of Prop. Black and Prop. Pov", 
                          "1 wk Ahead MAE as a funct. of Total Population",
                          "1 wk Ahead MAE as a funct. of Total Cases",
                          "1 wk Ahead MAE as a funct. of Cases and Minority Prop.",
                          "4 wk Ahead MAE as a funct. of Prop. Black and Prop. Pov",
                          "4 wk Ahead MAE as a funct. of Total Population",
                          "4 wk Ahead MAE as a funct. of Total Cases",
                          "4 wk Ahead MAE as a funct. of Cases and Minority Prop.")

dataTable <- as.table(dataMatrix)
kableTable <- kable(dataTable, format = "simple", align = 'l') 
kableTable

```








